name: CI-CD-pipline-AWS
env: 
  S3Bucket: "github-actins"
  Aplication_name  : "action-beanstock"
  BS_Eviroment_name: "ActionBeanstock-env"
  Deploy_name      : "ActionBeanstock-env_${{ github.sha }}.zip"
  AWS_Region_name  : "us-west-2" 

on:
  push:
    branches: 
      - master
 

jobs:
  CI:
   runs-on: ubuntu-latest 
   
 
   steps:
   
     - name: Git clone our repo
       uses: actions/checkout@v2

     - name: Create zip
       run: zip -r ${{ env.Deploy_name }} ./ -x*.git*
      
     - name: Configure my AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
        aws-access-key-id: ${{ secrets.AWS }}
        aws-secret-key-id: ${{ secrets.AWS_Secret_key }}
        aws-region: ${{ env.AWS_Region_name }} 
      
     - name: Copy ZIP in S3 bucket
       run: aws s3 cp ${{ env.Deploy_name }} s3://{{ env.S3Bucket }}/
     - name: congratulations
       run: echo "Congratulation with good build"

     
  
 

  
  
    
      

  
