

name: CI-CD-pipline-AWS
env: 
  S3Bucket: "github-actins"
  Aplication_name  : "action-beanstock"
  BS_Eviroment_name: "ActionBeanstock-env"
  Deploy_name      : "ActionBeanstock-env_${{ github.sha }}.zip"
  AWS_Region_name  : "us-west-2" 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  CI:
   runs-on: ubuntu-latest 
   
 
    steps:
    - name: Git clone our repo
    - uses: actions/checkout@v2


    - name: Create zip
      run: zip -r ${{ env.Deploy_name }} ./ -x*.git*

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
